Add user page with chat window
FI-61m-distributed-systems/payment_and_chat_web_gui pull request #3
Opened 2017-05-09 13:20 UTC by dmytrenko02

В наступний commit ввійде "Add actions panel for user cabinet"

2017-05-09 13:37 UTC, semensan requested changes
к тому же чат явно не тестировался нормально
попробуй послать 20 сообщений, посмотри куда всё уедет

2017-05-09 13:37 UTC, semensan commented on user_cabinet.html
> +					<div id="my_balance">My balance: <div id="amount">1000$</div></div>
деньги ты должен будешь запрашивать из другого микросервиса
сделай заглушку

2017-05-09 13:37 UTC, semensan commented on user_cabinet.html
> +					<div id="chat_massage">
сообщения тоже нужно запрашивать, тоже ставь заглушку
и ещё, представь что не ты отправляешь сообщение, а тебе приходит
этот код явно не сработает

2017-05-09 16:22 UTC, dmytrenko02 commented
Тоді я приберу фунціонал з addMessage в jsript, а додам лише обробку "чи не пусте поле під час надсилання повідомлення".
При натисканні кнопки "Send" : 1) викликатиметься функція сервісного рівня, що оброблятиме й зберігатиме повідомлення, 2) відбуватиметься redirect на цю ж сторінку user_cabinet.html. Ще одна функція сервісного рівня генеруватиме список із всіх повідомлень, які відображатимуться в межах екрана в полі зі скрулом, відповідно до вже написаного шаблону.

2017-05-09 16:26 UTC, semensan commented
відбуватиметься redirect на цю ж сторінку user_cabinet.html
эээ, Олег, ты про асинхронные запросы вообще слышал?
читай AJAX

2017-05-09 16:28 UTC, semensan commented
я даже свой курсач откопал с первых курсов
лови в вк

2017-05-09 16:30 UTC, dmytrenko02 commented
Розбиратимуся з Ajax.

2017-05-09 16:30 UTC, semensan commented
Ще одна функція сервісного рівня генеруватиме список із всіх повідомлень, які відображатимуться в межах екрана
сервис не знает про экран
я где-то писал в чате про функции сервиса сообщений
твоя задача правильно сделать запросы их отправки, получения и вменяемый вывод

2017-05-13 11:43 UTC, dmytrenko02 commented
В останньому commit я показав, як будуть виводитись список повідомлень на екран.
Заглушку для amount створив (відпиши наступним коментрарієм, чи так вона має виглядати у JScript).
Заглушку для повідомлень я ще робитиму.

2017-05-13 11:50 UTC, semensan commented
заглушка ок

2017-05-13 11:53 UTC, dmytrenko02 commented
Нічого, що в коді буде перемішано і JS, і PHP?
В моєму розумінні, це нормально.

2017-05-13 11:58 UTC, semensan commented
конечно нормально
они не взаимозаменяемы

2017-05-13 12:06 UTC, dmytrenko02 commented
Тоді попередню заглушку (для amount) і наступні переписати на php?
Будем тепер смикати функції, використовуючи php-код, а не JScript, напряму прописуючи <?php echo Get_amount() >  ?

2017-05-13 12:09 UTC, semensan commented
если ты считаешь что это будет проще...
можешь конечно, но думаю то что можно сделать на JS пусть пока работает на JS

2017-05-13 12:13 UTC, dmytrenko02 commented
Ок.
Тоді php залишаю для session і для випадків, коли php мені здаватиметься ближчим і простішим у використанні, ніж JScript.

2017-05-13 12:31 UTC, dmytrenko02 commented
Важливе питання! Тепер мені доведеться працювати з іншою папкою, що носитиме назву віртуального домену. В ній буде папка з назвою "www". Як мені перенести всі напрацювання в папку "www", щоб не поламати існуючий репозиторій? Як зробити так, щоб система зрозуміла мене правильно?
(Вміст папки payment_and_chat_web_gui потрібно перенести у папку "www") .

2017-05-13 12:35 UTC, semensan commented
да как обычно
git понимает перенос файлов

2017-05-13 12:37 UTC, dmytrenko02 commented
Головне, що переноситься папка .git ?
Він переіменує віддалений репозиторій після наступного push? Якщо так, то як він тепер називатиметься: "www"?

2017-05-13 12:48 UTC, dmytrenko02 commented
Все, протестував на іншому репозитор. Назва папки буде різною, а вміст буде синхронізовуватись.

2017-05-13 14:57 UTC, dmytrenko02 commented
Просто змінив формат файлу user_cabinet із .html в .php
Зараз працюю над  заглушкою для чату.

2017-05-13 18:48 UTC, dmytrenko02 commented
Далі впроваджуватиму Ajax.

2017-05-16 16:20 UTC, dmytrenko02 commented
Тепер асинхронно виводяться повідомлення чату та сума коштів, які є на рахунку користувача.

2017-05-16 16:21 UTC, dmytrenko02 commented
Наступним commit додам session.

2017-05-17 13:43 UTC, semensan requested changes
итак начнём
1) поправь сообщения коммитов
блок - block
заглушка - stub
ajax - технология а не выполненная работа
2) табы везде разных размеров, местами жутко хромое выравнивание, кодировка тоже разная
сделай код читаемым
(и поменяй у себя в IDE табы на 3 пробела)
3) что за functions.py?
да ещё пустой
4) то о чём мы говорили
5) тестировал, сообщения в чате не добавляются
6) дальше по тексту...

2017-05-17 13:43 UTC, semensan commented on auth.php
> +    header("Location:  index.html");/*редерект обратно якщо помилка авторизації*/
намешал всего
и транслит и рус. и укр.
в случаях кривой транслитерации используй лучше оригинал (redirect)
если сложно сформулировать в одном варианте, переформулируй в другой

2017-05-17 13:43 UTC, semensan commented on bloks/amount.php
> +  $amount = /*Get_amount()*/"1000"; /*виклик ф-ї, що повертає суму коштів у форматі string*/
зачем php? такое как по мне лучше в JS делать

2017-05-17 13:43 UTC, semensan commented on bloks/messages.php
> +  $messages = null/*getAllMessages(30)*/;/*a-�, �� ����������� ����� 2��2 �� 30-�� ������� ����������*/
как и это
асинхронные запросы лучше прямо из JS
что мешает для этих функций отдельный файл скриптов сделать?

2017-05-17 13:43 UTC, semensan commented on start.php
> +	session_start();
зачем целый файл на это?

2017-05-17 13:43 UTC, semensan commented on logout.php
> +  unset($_POST["password"]);
не уверен что пароль всё время должен лежать в сессии

2017-05-17 14:44 UTC, dmytrenko02 commented on start.php
> +	session_start();
Згоден.

2017-05-17 14:48 UTC, dmytrenko02 commented on logout.php
> +  unset($_POST["password"]);
Я теж так подумав. Тому, де потрібно, я підчищу сесію.

2017-05-19 20:44 UTC, dmytrenko02 commented
Повідомлення в чаті оновлюються доволі швидко, тому із функціоналу я прибрав вивід повідомлення одразу на екран (тому кнопка "send" не відображає щойно відправлене повідомлення). Щоб побачити, як виводяться повідомленя - змінюй руками матрицю у файлі functions.php.

2017-05-19 20:48 UTC, dmytrenko02 commented
І мені поки простіше, щоб деякі функціі' були у файлі functions.php. Тому потім, якщо зможу перенести і'х у JS,  то зроблю. Але якщо це не критично, то залишу як є.

2017-05-20 07:33 UTC, semensan reviewed
не усложняй код где не нужно
и открывай, пожалуйста, переводчик как садишься за работу
asynchronous (Add asynchronius requests )
да, и поменяй amount на money или что-то вроде, ни о чём же не говорит

2017-05-20 07:33 UTC, semensan commented on auth.php
> +   $password = md5($password);
почему бы не md5(htmlspecialchars(...))?

2017-05-20 07:33 UTC, semensan commented on blocks/amount.php
> +	include "functions.php";
tab

2017-05-20 07:33 UTC, semensan commented on blocks/amount.php
> +   echo" $";
зачем всё усложнять?
echo getAmount(), " $"

2017-05-20 07:33 UTC, semensan commented on blocks/functions.php
> +   return $amount;
короче здесь и дальше упрощай код
если переменная создаётся для одного использования, возможно она вообще не нужна?

2017-05-20 07:33 UTC, semensan commented on blocks/messages.php
> +	include "functions.php";
tab
короче дальше тоже

2017-05-20 07:33 UTC, semensan commented on script.js
> +function getAmount(){
если ты перенёс всё в php то это зачем?

2017-05-20 07:33 UTC, semensan commented on script.js
>  		alert("Username is incorrect!");
ты пробовал вводить не правильно всё?
такая куча alert'ов сильно мешает
если не делаешь вывод в саму страницу, сделай хоть на всё один alert с автогенерящимся сообщением

2017-05-20 07:33 UTC, semensan commented on script.js
> +  if (valid &&  valid1) {
поправь табуляцию

2017-05-20 07:33 UTC, semensan commented on script.js
> +		fun_add_Message();/*виклик ф-ї, що надсилає повідомлення до БД*/
а сама функция где?
я не нашёл

2017-05-20 07:33 UTC, semensan commented on script.js
> +function addMessage(){
если не хочешь чтобы эта функция сама добавляла отправленное сообщение, сделай здесь хоть внеплановую синхронизацию
и переименуй в sendMessage

2017-05-20 09:59 UTC, semensan commented on script.js
> +  var receiver_pattern = /[0-9a-z]{4,20}/;
дублирование - плохо
сделай функции на проверку таких данных

2017-05-20 11:45 UTC, dmytrenko02 commented
1) В мене з відступами все нормально. Не розумію, чому git так їх відображає. 
2) Там, де змінні використовуються один раз, я предаватиму в них результат http-запиту. 
3) Дублювання коду поки залишилось.

2017-05-22 14:37 UTC, semensan commented
1. как видишь не нормально
скорее всего у тебя часть табов осталась табами, а часть пробелы
просто заставь IDE отформатировать код за тебя и радуйся жизни
2. вот когда будешь тогда и сделаешь, да и то скорее всего наплодишь лишних переменных
3. чини

2017-05-25 15:49 UTC, semensan approved these changes

2017-05-25 15:49 UTC, merged